wandb_version: 1

exp_name:
  desc: null
  value: RL
gym_id:
  desc: null
  value: LunarLander-v2
learning_rate:
  desc: null
  value: 0.00025
seed:
  desc: null
  value: null
total_timesteps:
  desc: null
  value: 25000
torch_deterministic:
  desc: null
  value: true
cuda:
  desc: null
  value: true
track:
  desc: null
  value: true
wandb_project_name:
  desc: null
  value: ppo-implementation-details
wandb_entity:
  desc: null
  value: null
num_envs:
  desc: null
  value: 4
num_steps:
  desc: null
  value: 128
anneal_lr:
  desc: null
  value: true
gae:
  desc: null
  value: true
gamma:
  desc: null
  value: 0.99
gae_lambda:
  desc: null
  value: 0.95
num_minibatches:
  desc: null
  value: 4
update_epochs:
  desc: null
  value: 4
norm_adv:
  desc: null
  value: true
clip_coef:
  desc: null
  value: 0.2
clip_vloss:
  desc: null
  value: true
ent_coef:
  desc: null
  value: 0.01
vf_coef:
  desc: null
  value: 0.5
max_grad_norm:
  desc: null
  value: 0.5
target_kl:
  desc: null
  value: null
_wandb:
  desc: null
  value:
    code_path: code/RL.py
    python_version: 3.11.4
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1687995290.074817
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      - 35
      4: 3.11.4
      5: 0.15.4
      8:
      - 5
