wandb_version: 1

_wandb:
  desc: null
  value:
    code_path: code/ppo.py
    python_version: 3.11.4
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1688453781.149623
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 23
      4: 3.11.4
      5: 0.15.4
      8:
      - 5
